<a href="https://colab.research.google.com/github/ana-leticia-cabral/estudos-python/blob/main/Exercicios_AnaliseDeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios práticos de Python e NumPy
## Desenvolvido para Analista de dados júnior focados no mercado de trabalho e transição para Ciência de dados.


1. Python Estrutural de Variáveis de Coleção (1 a 25)
2. Introdução ao NumPy - Criação, Tipagem e Indexação Avançada (26 a 50)
3. Operações Vetorizadas, Funções Estatísticas e Broadcasting (51 a 75)
4. Transformação de Formato e Casos do Mundo real (76 a 100)

### Python Estrutural e Variáveis de Coleção (Exercícios 1 a 25)

1. Situação: Dados extraídos de uma tabela do PostgreSQL contêm valores de faturamento salvos como texto formatado ('R$ 1.500,50').


- Objetivo: Escreva uma função em Python que receba essa string, remova o símbolo monetário, os pontos de milhar, substitua a vírgula por ponto e converta o resultado para o tipo float.

In [1]:
def limpa_strings_moeda(faturamento: str) -> float:

  """
    Converte uma string de valor monetário para float.

    A função remove símbolos como "R$", separadores de milhar (.)
    e substitui vírgula por ponto, permitindo a conversão para float.

    Exemplo:
        "R$ 1.234,56" -> 1234.56

    :param faturamento: Valor monetário em formato string.
    :return: Valor convertido para float.
    :raises ValueError: Caso a conversão não seja possível.

  """


  try:
    faturamento = float(faturamento)
    print('A função espera um argumento do tipo String para valor monetário. Contendo "R$", ".", "," ')
  except ValueError as e:

    if "R$" not in faturamento and "." not in faturamento and "," not in faturamento:
      print('A função espera apenas caracteres de valores monetários: "R$", ".", "," ')
    else:
      if "R$" in faturamento:
        faturamento = faturamento.replace("R$", "")

      if "." in faturamento:
        faturamento = faturamento.replace(".", "")

      if "," in faturamento:
        faturamento = faturamento.replace(",", ".")

      faturamento = float(faturamento)
      return faturamento

In [2]:
print(limpa_strings_moeda("R$1.500,50"))
print(limpa_strings_moeda("1500.50"))
print(limpa_strings_moeda("abcde"))
print(limpa_strings_moeda("12345"))
print(limpa_strings_moeda(12345))


1500.5
A função espera um argumento do tipo String para valor monetário. Contendo "R$", ".", "," 
None
A função espera apenas caracteres de valores monetários: "R$", ".", "," 
None
A função espera um argumento do tipo String para valor monetário. Contendo "R$", ".", "," 
None
A função espera um argumento do tipo String para valor monetário. Contendo "R$", ".", "," 
None


2. Situação: Você exportou uma lista de IDs de clientes que interagiram com o suporte hoje, mas há muitos registros duplicados devido a interações repetidas.

- Objetivo: Utilize a estrutura de dados Set(conjunto) para filtrar apenas os os IDs únicos e retorne a quantidade total de clientes únicos atendidos.


In [3]:
def remove_duplicatas(lista: list) -> int:
    """
    Converte uma lista em um conjunto (set), removendo elementos duplicados.

    Exemplo:
        >>> remove_duplicatas([1, 2, 2, 2, 3, 4, 4, 5, 6, 7, 8, 9, 9, 10])
        {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

    :param lista: Lista contendo elementos, podendo haver valores duplicados.
    :return: Total de clientes únicos atendidos.
    :raises TypeError: Caso a entrada não seja uma lista.
    """

    if not isinstance(lista, list):
        raise TypeError("A função espera um objeto do tipo list")

    elementos_unicos = set(lista)
    return len(elementos_unicos)

In [4]:
print(remove_duplicatas([1, 2, 2, 2, 3, 4, 4, 5, 6, 7, 8, 9, 9, 10]))
print(remove_duplicatas([5, 5, 5, 5, 4, 3, 2]))


10
4


3. Situação: Simulando um JOIN do SQL. Você tem uma lista de dicionários contendo transações e outra contendo o cadastro dos clientes.

- Objetivo: Crie um script que use um dicionário indexado pelo ID do cliente para mapear o nome do cliente diretamente em cada registro da transação.

In [5]:
clientes = [
    {1 : "Ana"},
    {2 : "Carlos"},
    {3 : "Maria"}
]

In [6]:
transacoes = [
    {1: 100.0},
    {2: 250.0},
    {1: 50.0},
    {3: 300.0},
    {2: 150.0}
]

In [7]:
def cruza_tabelas(*, transacoes: list, clientes: list) -> None:
    """
    Realiza o cruzamento (inner join) entre duas listas de dicionários,
    relacionando transações com clientes por meio do ID.

    Cada transação e cada cliente devem estar no formato:
        transacoes: [{id_cliente: valor}]
        clientes: [{id_cliente: nome}]

    Exemplo:
        >>> cruza_tabelas([{1: 100.0}], [{1: "Ana"}])
        Nome do cliente: Ana. Registro da transação: 100.0

    :param transacoes: Lista de dicionários contendo as transações dos clientes.
    :param clientes: Lista de dicionários contendo os nomes dos clientes.
    :return: None
    :raises TypeError: Caso alguma das entradas não seja uma lista.
    """

    if not isinstance(transacoes, list) or not isinstance(clientes, list):
        raise TypeError("A função espera listas como entrada")

    for t in transacoes:
        for c in clientes:
            if list(t.keys())[0] == list(c.keys())[0]:
                print(
                    f'Nome do cliente: {list(c.values())[0]}. '
                    f'Registro da transação: {list(t.values())[0]}'
                )

cruza_tabelas(transacoes = transacoes, clientes = clientes)

Nome do cliente: Ana. Registro da transação: 100.0
Nome do cliente: Carlos. Registro da transação: 250.0
Nome do cliente: Ana. Registro da transação: 50.0
Nome do cliente: Maria. Registro da transação: 300.0
Nome do cliente: Carlos. Registro da transação: 150.0


In [8]:
def cruza_tabelas(transacoes: list, clientes: list) -> None:


    """
    Realiza o cruzamento (inner join) entre duas listas de dicionários,
    relacionando transações com clientes por meio do ID.

    Cada transação e cada cliente devem estar no formato:
        transacoes: [{id_cliente: valor}]
        clientes: [{id_cliente: nome}]

    Exemplo:
        >>> cruza_tabelas([{1: 100.0}], [{1: "Ana"}])
        Nome do cliente: Ana. Registro da transação: 100.0

    :param transacoes: Lista de dicionários contendo as transações dos clientes.
    :param clientes: Lista de dicionários contendo os nomes dos clientes.
    :return: None
    :raises TypeError: Caso alguma das entradas não seja uma lista.
    """


    if not isinstance(transacoes, list) or not isinstance(clientes, list):
        raise TypeError('A função espera objetos do tipo list')

    clientes_dict = {}

    for c in clientes:
        key = list(c.keys())[0]
        value = list(c.values())[0]
        clientes_dict[key] = value

    for t in transacoes:
        id_cliente = list(t.keys())[0]
        valor = list(t.values())[0]

        nome = clientes_dict[id_cliente]
        print(f'Nome do cliente: {nome}. Registro da transação: {valor}')

cruza_tabelas(transacoes, clientes)


Nome do cliente: Ana. Registro da transação: 100.0
Nome do cliente: Carlos. Registro da transação: 250.0
Nome do cliente: Ana. Registro da transação: 50.0
Nome do cliente: Maria. Registro da transação: 300.0
Nome do cliente: Carlos. Registro da transação: 150.0


4. Situação: Uma lista armazena o status de clientes no fim do mês: 'Ativo', 'Cancelado', 'Ativo', 'Ativo', 'Cancelado'.

- Objetivo: Calcule a taxa de Churn percentual(total de cancelados dividido pelo total de clientes na lista) usando métodos nativos de contagem de listas.

In [9]:
status_clientes = ['Ativo', 'Cancelado', 'Ativo', 'Ativo', 'Cancelado']
total_clientes = len(status_clientes)
total_cancelados = status_clientes.count('Cancelado')
porcentagem = (total_cancelados/total_clientes) * 100

print(f'Taxa de Churn: {porcentagem}%')

Taxa de Churn: 40.0%


5. Situação: O estoque do PowerBI consome uma lista de tuplas no formato (Nome_produto, Qtd_Estoque, Estoque_minimo).

- Objetivo: Utilizando um loop for e condicionais, filtre e crie uma nova lista apenas com os produtos cujo estoque atual está abaixo do estoque mínimo.

In [10]:
produtos = [
    ("Notebook", 10, 5),
    ("Mouse", 100, 20),
    ("Teclado", 6, 15)
]

In [11]:
def estoque_powerbi_abaixo(lista: list) -> list:
  """
  Filtra produtos cujo estoque atual está abaixo do estoque mínimo.

  Exemplo:
        >>> estoque_powerbi_abaixo([("Notebook", 10, 5), ("Mouse", 100, 20), ("Teclado", 6, 15)])
        ['Teclado']

  :param lista: Lista de tuplas no formato (Nome_produto, Qtd_Estoque, Estoque_minimo)
  :return: list
  :raises TypeError: Caso a entrada não seja uma lista.

  """

  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo list.')


  produtos_abaixo = []
  for produto in lista:
    if produto[1] < produto[2]:
      produtos_abaixo.append(produto[0])

  return produtos_abaixo


estoque_powerbi_abaixo(produtos)

['Teclado']

6. Situação: O setor comercial solicitou um reajuste inflacionário de 6.5% em toda a tabela de preço de produtos.

- Objetivo: A partir de uma lista de floats representando os preços atuais, utilize List Comprehension para gerar a nova lista com os valores reajustados.

In [12]:
precos_produtos = [10.99, 25.50, 7.30, 100.00, 3.45]

In [13]:
def reajuste_inflacionario(precos_produtos: list[float]) -> list[float]:
  """
  Realiza reajuste inflacionário de 6.5% de uma lista de produtos.

  Exemplo:
        >>> reajuste_inflacionario([10.99, 25.50, 7.30, 100.00, 3.45])
        [11.7, 27.16, 7.77, 106.5, 3.67]

  :param precos_produtos: Lista de floats que representa os preços dos produtos.
  :return: Lista com preços reajustados.
  :raises TypeError: Caso a entrada não seja uma lista.

  """

  if not isinstance(precos_produtos, list):
    raise TypeError('A função espera um objeto do tipo list.')

  valores_novos = [round(valor + (valor * (0.065)), 2) for valor in precos_produtos]
  return valores_novos




reajuste_inflacionario(precos_produtos)

[11.7, 27.16, 7.77, 106.5, 3.67]

7. Situação: Uma lista de dicionários contém faturamentos no formato {'regiao':'Sudeste, 'valor':12000}

- Objetivo: Escreva um algoritmo que percorra a lista e acumule o valor total faturado por cada região dentro de um dicionário agregador.

In [14]:
dados_regiao = [
    {'regiao': 'Sudeste', 'valor': 12000},
    {'regiao': 'Sul', 'valor': 8000},
    {'regiao': 'Nordeste', 'valor': 6000},
    {'regiao': 'Centro-Oeste', 'valor': 4000},
    {'regiao': 'Norte', 'valor': 3000},
    {'regiao': 'Sudeste', 'valor': 15000},
    {'regiao': 'Sul', 'valor': 7000}
]

In [15]:
def total_faturado_regiao(faturamentos: list[dict]) -> dict:

  """
  Calcula o total faturado por região a partir de uma lista de dicionários.

  Cada elemento da lista deve conter as chaves:
  - 'regiao': nome da região
  - 'valor': valor do faturamento

  A função percorre a lista e acumula os valores por região,
  retornando um dicionário agregador no formato {regiao: total_faturado}.

  Exemplo:
        >>> dados = [
        ...     {'regiao': 'Sudeste', 'valor': 12000},
        ...     {'regiao': 'Sul', 'valor': 8000},
        ...     {'regiao': 'Sudeste', 'valor': 15000}
        ... ]
        >>> total_faturado_regiao(dados)
        {'Sudeste': 27000, 'Sul': 8000}

  :param faturamentos: Lista de dicionários contendo os faturamentos por região.
  :return: Dicionário com o total faturado por região.
  :raises TypeError: Caso a entrada não seja uma lista.
  """

  if not isinstance(faturamentos, list):
    raise TypeError('A função espera um objeto do tipo list.')

  dicionario_agregador = {}

  for faturamento_regiao in faturamentos:
    regiao = faturamento_regiao['regiao']
    valor = faturamento_regiao['valor']

    if regiao in dicionario_agregador:
      dicionario_agregador[regiao] += valor
    else:
      dicionario_agregador[regiao] = valor

  return dicionario_agregador


total_faturado_regiao(dados_regiao)


{'Sudeste': 27000,
 'Sul': 15000,
 'Nordeste': 6000,
 'Centro-Oeste': 4000,
 'Norte': 3000}

8. Situação: Você recebeu uma lista desordenada com os volumes de venda de 20 produtos diferentes.

- Objetivo: Ordene a lista de forma decrescente e extraia os 5 maiores valores sem utilizar bibliotecas externas.

In [16]:
vendas = [
    ("Produto A",  3200),
    ("Produto B",  870),
    ("Produto C",  5100),
    ("Produto D",  420),
    ("Produto E",  7800),
    ("Produto F",  1350),
    ("Produto G",  9200),
    ("Produto H",  630),
    ("Produto I",  2900),
    ("Produto J",  4400),
    ("Produto K",  110),
    ("Produto L",  6700),
    ("Produto M",  3050),
    ("Produto N",  800),
    ("Produto O",  5900),
    ("Produto P",  2100),
    ("Produto Q",  7300),
    ("Produto R",  490),
    ("Produto S",  1800),
    ("Produto T",  3600),
]

In [17]:
def ordena_volume_vendas(lista: list[tuple]) -> None:


  """
  Ordena uma lista de produtos vendidos de forma decrescente e
  extrai os 5 maiores elementos dela.

  Exemplo:
      >>> vendas = [
      ...     ("Produto A",  3200),
      ...     ("Produto B",  870),
      ...     ("Produto C",  5100),
      ...     ("Produto D",  420),
      ...     ("Produto E",  7800),
      ...     ("Produto F",  1350),
      ...     ("Produto G",  9200),
      ...     ("Produto H",  630),
      ...     ("Produto I",  2900),
      ...     ("Produto J",  4400),
      ...     ("Produto K",  110),
      ...     ("Produto L",  6700),
      ...     ("Produto M",  3050),
      ...     ("Produto N",  800),
      ...     ("Produto O",  5900),
      ...     ("Produto P",  2100),
      ...     ("Produto Q",  7300),
      ...     ("Produto R",  490),
      ...     ("Produto S",  1800),
      ...     ("Produto T",  3600),
      ... ]
      >>> ordena_volume_vendas(vendas)
      Lista ordenada de forma decrescente: [('Produto G', 9200), ('Produto E', 7800), ('Produto Q', 7300), ('Produto L', 6700), ('Produto O', 5900), ('Produto C', 5100), ('Produto J', 4400), ('Produto T', 3600), ('Produto A', 3200), ('Produto M', 3050), ('Produto I', 2900), ('Produto P', 2100), ('Produto S', 1800), ('Produto F', 1350), ('Produto B', 870), ('Produto N', 800), ('Produto H', 630), ('Produto R', 490), ('Produto D', 420), ('Produto K', 110)]
      5 maiores valores: [('Produto G', 9200), ('Produto E', 7800), ('Produto Q', 7300), ('Produto L', 6700), ('Produto O', 5900)]

  :param lista: Lista de tuplas contendo produtos vendidos.
  :return: None
  :raises TypeError: Caso a entrada não seja uma lista.
  """


  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo List')


  lista_ordenada = sorted(lista, key= lambda x: x[1], reverse = True) # Percorre cada tupla da lista e usa o segundo elemento como critério de ordenação.
  print(f'Lista ordenada de forma decrescente: {lista_ordenada}')
  print(f'5 maiores valores: {lista_ordenada[0:5]}')

ordena_volume_vendas(vendas)

Lista ordenada de forma decrescente: [('Produto G', 9200), ('Produto E', 7800), ('Produto Q', 7300), ('Produto L', 6700), ('Produto O', 5900), ('Produto C', 5100), ('Produto J', 4400), ('Produto T', 3600), ('Produto A', 3200), ('Produto M', 3050), ('Produto I', 2900), ('Produto P', 2100), ('Produto S', 1800), ('Produto F', 1350), ('Produto B', 870), ('Produto N', 800), ('Produto H', 630), ('Produto R', 490), ('Produto D', 420), ('Produto K', 110)]
5 maiores valores: [('Produto G', 9200), ('Produto E', 7800), ('Produto Q', 7300), ('Produto L', 6700), ('Produto O', 5900)]


9. Situação: O time de compliance de prevenção a fraudes precisa auditar transações muito acima do padrão da empresa.

- Objetivo: Dada uma lista de valores de transações, calcule a média aritmética simples e liste todas as transações que são 3 vezes maiores que a média.

In [18]:
transacoes = [3500.00, -150.75, -25.40, -220.10, -80.00, 500.00, -120.00, -45.30, -35.00, 200.00]

In [19]:
def identifica_outliers(lista: list[float]) -> list[float]:

  """
  Dado uma lista com valores de transações, identifica possíveis valores suspeitos
  Exemplo:
      >>> transacoes = [
      ...     3500.00, -150.75, -25.40, -220.10, -80.00, 500.00, -120.00, -45.30, -35.00, 200.00]
      >>> identifica_outliers(transacoes)
      [3500.0]

  :param lista: Lista de transacoes
  :return: lista de transacoes suspeitas
  :raises TypeError: Caso a entrada não seja uma lista.
  """

  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo List')



  outliers = []

  quantidade_transacoes = len(lista)
  soma_transacoes = sum(lista)
  media_transacoes = (soma_transacoes / quantidade_transacoes)
  transacoes_suspeitas = (media_transacoes * 3)

  for transacao in lista:
    if transacao >= transacoes_suspeitas:
      outliers.append(transacao)

  return outliers


identifica_outliers(transacoes)


[3500.0]

10. Situação: o log do sistena registra datas no formato americano 'YYYY-MM-DD', mas o relatório final do Tableau exige 'DD/MM/YYYY'

- Objetivo: Escreva um script que use manipulação de strings (split e fatiamento) para converter uma lista de datas para o formato brasileiro)

In [20]:
datas = [
    "2026-06-01",
    "2026-06-02",
    "2026-06-03",
    "2026-06-04",
    "2026-06-05",
    "2026-06-06",
    "2026-06-07"
]

In [21]:
from datetime import datetime

def valida_lista_str(lista: list):

  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo List.')

  if len(lista) == 0:
    raise ValueError('A função não espera uma lista vazia')

  for item in lista:
    if not isinstance(item, str):
      raise TypeError(f'Valor inválido encontrado: {item}')

    try:
      datetime.strptime(item, '%Y-%m-%d')
    except ValueError:
      raise ValueError(f'Data inválida: {item}')

  return True

In [22]:
def formata_data_br(formato_americano: list[str]) -> list[str]:

  """
  Dado uma lista com datas em formato americano "YYYY-MM-DD", os converte para o formato brasileiro "DD/MM/YYYY".
  Exemplo:
      >>> datas = [
      ... "2026-06-01",
      ... "2026-06-02",
      ... "2026-06-03",
      ... "2026-06-04",
      ... "2026-06-05",
      ... "2026-06-06",
      ... "2026-06-07"
      ]
      >>> formata_data_br(datas)
      ['01/06/2026',
       '02/06/2026',
       '03/06/2026',
       '04/06/2026',
       '05/06/2026',
       '06/06/2026',
       '07/06/2026']

  :param formato_americano: Lista com datas no formato "YYYY-MM-DD".
  :return: lista com datas no formato "DD/MM/YYYY".
  :raises TypeError: Caso a entrada não seja uma lista com valores String.
  :raises ValueError: Caso o item da lista não seja uma data no formato "YYYY-MM-DD".
  """

  if valida_lista_str(formato_americano):

    formato_brasileiro = []

    for data in formato_americano:
      data_br = data[8:10] + '/' + data[5:7] + '/' + data[:4]
      formato_brasileiro.append(data_br)
    return formato_brasileiro

formata_data_br(datas)

['01/06/2026',
 '02/06/2026',
 '03/06/2026',
 '04/06/2026',
 '05/06/2026',
 '06/06/2026',
 '07/06/2026']

11. Situação: dois servidores diferentes geraram listas de mensagens de erros durante uma falha na pipeline de dados.

- Objetivo: Combine as duas listas em uma única estrutura de dados que elimine automaticamente erros idênticos repetidos entre os servidores.

In [23]:
erros_servidor_1 = [
    "2026-06-15 10:01:23 - ERROR - Falha ao conectar ao banco de dados",
    "2026-06-15 10:02:10 - ERROR - Timeout ao consumir API externa",
    "2026-06-15 10:03:45 - ERROR - Payload inválido recebido no endpoint /ingest",
    "2026-06-15 10:05:02 - ERROR - Erro ao parsear JSON de entrada",
    "2026-06-15 10:06:30 - ERROR - Falha de autenticação no serviço de ingestão"
]

erros_servidor_2 = [
    "2026-06-15 10:01:50 - ERROR - Job ETL falhou ao iniciar",
    "2026-06-15 10:02:10 - ERROR - Timeout ao consumir API externa",
    "2026-06-15 10:03:00 - ERROR - Falha ao conectar ao banco de dados",
    "2026-06-15 10:04:12 - ERROR - Erro de divisão por zero na transformação",
    "2026-06-15 10:05:02 - ERROR - Erro ao parsear JSON de entrada",
    "2026-06-15 10:06:00 - ERROR - Coluna 'id_cliente' ausente no dataset",
    "2026-06-15 10:07:20 - ERROR - Conexão perdida com cluster Spark"
]

In [24]:
def valida_lista_str(lista: list):

  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo List.')

  if len(lista) == 0:
    raise ValueError('A função não espera uma lista vazia')

  for item in lista:
    if not isinstance(item, str):
      raise TypeError(f'Valor inválido encontrado: {item}')

  return True

In [25]:
def remove_erros_duplicados(servidor_1: list[str], servidor_2: list[str]) -> list[str]:

  """
  Duas listas que contém mensagem de erros durante uma falha na pipeline de dados, serão
  unidas para encontrar os erros que estão duplicados e removê-los.
  Exemplo:
      >>> erros_servidor_1 = [
      ... "2026-06-15 10:01:23 - ERROR - Falha ao conectar ao banco de dados",
      ... "2026-06-15 10:02:10 - ERROR - Timeout ao consumir API externa",
      ... "2026-06-15 10:03:45 - ERROR - Payload inválido recebido no endpoint /ingest",
      ... "2026-06-15 10:05:02 - ERROR - Erro ao parsear JSON de entrada",
      ... "2026-06-15 10:06:30 - ERROR - Falha de autenticação no serviço de ingestão"
       ]
     >>> erros_servidor_2 = [
     ... "2026-06-15 10:01:50 - ERROR - Job ETL falhou ao iniciar",
     ... "2026-06-15 10:02:10 - ERROR - Timeout ao consumir API externa",
     ... "2026-06-15 10:03:00 - ERROR - Falha ao conectar ao banco de dados",
     ... "2026-06-15 10:04:12 - ERROR - Erro de divisão por zero na transformação",
     ... "2026-06-15 10:05:02 - ERROR - Erro ao parsear JSON de entrada",
     ... "2026-06-15 10:06:00 - ERROR - Coluna 'id_cliente' ausente no dataset",
     ... "2026-06-15 10:07:20 - ERROR - Conexão perdida com cluster Spark"
      ]

      >>> remove_erros_duplicados(erros_servidor_1, erros_servidor_2)
        ['2026-06-15 10:01:23 - ERROR - Falha ao conectar ao banco de dados',
         '2026-06-15 10:01:50 - ERROR - Job ETL falhou ao iniciar',
         '2026-06-15 10:02:10 - ERROR - Timeout ao consumir API externa',
         '2026-06-15 10:03:00 - ERROR - Falha ao conectar ao banco de dados',
         '2026-06-15 10:03:45 - ERROR - Payload inválido recebido no endpoint /ingest',
         '2026-06-15 10:04:12 - ERROR - Erro de divisão por zero na transformação',
         '2026-06-15 10:05:02 - ERROR - Erro ao parsear JSON de entrada',
         "2026-06-15 10:06:00 - ERROR - Coluna 'id_cliente' ausente no dataset",
         '2026-06-15 10:06:30 - ERROR - Falha de autenticação no serviço de ingestão',
         '2026-06-15 10:07:20 - ERROR - Conexão perdida com cluster Spark']

  :param servidor_1: Lista com mensagens de erro do primeiro servidor.
  :param servidor_2: Lista com mensagens de erro do segundo servidor.
  :return: lista com os erros duplicados removidos.
  :raises TypeError: Caso a entrada não seja uma lista com valores String.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  if valida_lista_str(servidor_1) and valida_lista_str(servidor_2):
    todos_erros = servidor_1 + servidor_2
    todos_erros = set(todos_erros)

    todos_erros = list(todos_erros)
    todos_erros.sort()


    return todos_erros

remove_erros_duplicados(erros_servidor_1, erros_servidor_2)

['2026-06-15 10:01:23 - ERROR - Falha ao conectar ao banco de dados',
 '2026-06-15 10:01:50 - ERROR - Job ETL falhou ao iniciar',
 '2026-06-15 10:02:10 - ERROR - Timeout ao consumir API externa',
 '2026-06-15 10:03:00 - ERROR - Falha ao conectar ao banco de dados',
 '2026-06-15 10:03:45 - ERROR - Payload inválido recebido no endpoint /ingest',
 '2026-06-15 10:04:12 - ERROR - Erro de divisão por zero na transformação',
 '2026-06-15 10:05:02 - ERROR - Erro ao parsear JSON de entrada',
 "2026-06-15 10:06:00 - ERROR - Coluna 'id_cliente' ausente no dataset",
 '2026-06-15 10:06:30 - ERROR - Falha de autenticação no serviço de ingestão',
 '2026-06-15 10:07:20 - ERROR - Conexão perdida com cluster Spark']

12. Situação: o banco de dados antigo usa códigos numéricos para categorias de produto, e você precisa migrar para descrições textuais.

- Objetivo: Crie um dicionário mapeando os códigos {1:'Eletrônicos', 2:'Eletrodomésticos} e aplique-o para traduzir uma lista de códigos de vendas.

In [26]:
codigos_vendas = [1, 2, 1, 1, 2, 2]
mapeamento = {
    1: 'Eletrônicos',
    2: 'Eletrodomésticos'
}

In [27]:
def valida_lista_int(lista: list):

  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo List.')

  if len(lista) == 0:
    raise ValueError('A função não espera uma lista vazia')

  for item in lista:
    if not isinstance(item, int):
      raise TypeError(f'Valor inválido encontrado: {item}')

  return True

In [28]:
def mapear_codigos(codigos: list[int]) -> list[str]:


  """
  Traduz uma lista de códigos de categorias em uma lista de descrições.
  Exemplo:
      >>> codigos_vendas = [1, 2, 1, 1, 2, 2]
      >>> mapeamento = {
      ... 1: 'Eletrônicos',
      ... 2: 'Eletrodomésticos'}
      >>> mapear_codigos(codigos_vendas)
          ['Eletrônicos',
           'Eletrodomésticos',
           'Eletrônicos',
           'Eletrônicos',
           'Eletrodomésticos',
           'Eletrodomésticos']

  :param codigos: Lista com os códigos das categorias.
  :return: Lista com as descrições dos códigos.
  :raises TypeError: Caso a entrada não seja uma lista com valores inteiros.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  if valida_lista_int(codigos):
    descricao = []

    for cd in codigos:
      if cd in mapeamento:
        desc = mapeamento[cd]
        descricao.append(desc)

  return descricao


mapear_codigos(codigos_vendas)

['Eletrônicos',
 'Eletrodomésticos',
 'Eletrônicos',
 'Eletrônicos',
 'Eletrodomésticos',
 'Eletrodomésticos']

13. Situação: para suavizar as oscilações diárias de acessos a um dashboard do PowerBI, o gestor pediu uma média móvel de 3 dias.

- Objetivo: dada uma lista com o número de acessos diários de uma semana, implemente um loop que calcule a média móvel de 3 dias.

In [29]:
acessos_semana = [120, 150, 170, 160, 200, 250, 220]


In [30]:
def media_movel_3_dias(acessos_diarios: list[int]) -> None:


  """
  Calcula a média móvel a cada 3 dias durante uma semana (7 dias)
  Exemplo:
      >>> acessos_semana = [120, 150, 170, 160, 200, 250, 220]
      >>> media_movel_3_dias(acessos_semana)
          146.66666666666666
          160.0
          176.66666666666666
          203.33333333333334
          223.33333333333334

  :param acessos_diarios: Lista com acessos diários.
  :return: None
  :raises TypeError: Caso a entrada não seja uma lista com valores inteiros.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  if valida_lista_int(acessos_diarios):

    janela = 3
    inicio = 0

    while inicio <= len(acessos_diarios) - janela:
        media = round((sum(acessos_diarios[inicio:inicio + janela]) / janela), 2)
        inicio = inicio + 1
        print(media)

In [31]:
media_movel_3_dias(acessos_semana)

146.67
160.0
176.67
203.33
223.33


14. Situação: A API de e-mail de marketing aceita o envio de no máximo 5 leads por requisição para evitar sobrecarga.

- Objetivo: Escreva uma função que receba uma lista com 23 e-mails e divida essa lista em uma lista de sublistas contendo até 5 e-mails cada.

In [32]:
emails = [
    "ana.silva@example.com",
    "bruno.santos@example.com",
    "carla.oliveira@example.com",
    "daniel.costa@example.com",
    "eduarda.lima@example.com",
    "felipe.rocha@example.com",
    "gabriela.alves@example.com",
    "henrique.melo@example.com",
    "isabela.ramos@example.com",
    "joao.pereira@example.com",
    "karina.gomes@example.com",
    "lucas.martins@example.com",
    "mariana.barbosa@example.com",
    "nicolas.teixeira@example.com",
    "olivia.ferreira@example.com",
    "paulo.cardoso@example.com",
    "quintino.araujo@example.com",
    "rafaela.dias@example.com",
    "samuel.nogueira@example.com",
    "talita.vieira@example.com",
    "victor.campos@example.com",
    "wilson.machado@example.com",
    "yasmin.fonseca@example.com"
]

In [33]:
def evita_sobrecarga_emails(emails: list[str]) -> list[list[str]]:

  """
  Recebe uma lista e a divide em sublistas com 5 itens de email cada.
  Exemplo:
      >>> emails = [
      ... "ana.silva@example.com",
      ... "bruno.santos@example.com",
      ... "carla.oliveira@example.com",
      ... "daniel.costa@example.com",
      ... "eduarda.lima@example.com",
      ... "felipe.rocha@example.com",
      ... "gabriela.alves@example.com",
      ... "henrique.melo@example.com",
      ... "isabela.ramos@example.com",
      ... "joao.pereira@example.com",
      ... "karina.gomes@example.com",
      ... "lucas.martins@example.com",
      ... "mariana.barbosa@example.com",
      ... "nicolas.teixeira@example.com",
      ... "olivia.ferreira@example.com",
      ... "paulo.cardoso@example.com",
      ... "quintino.araujo@example.com",
      ... "rafaela.dias@example.com",
      ... "samuel.nogueira@example.com",
      ... "talita.vieira@example.com",
      ... "victor.campos@example.com",
      ... "wilson.machado@example.com",
      ... "yasmin.fonseca@example.com" ]

      >>> evita_sobrecarga_email(emails)
          [['ana.silva@example.com',
            'bruno.santos@example.com',
            'carla.oliveira@example.com',
            'daniel.costa@example.com',
            'eduarda.lima@example.com'],

           ['felipe.rocha@example.com',
            'gabriela.alves@example.com',
            'henrique.melo@example.com',
            'isabela.ramos@example.com',
            'joao.pereira@example.com'],

           ['karina.gomes@example.com',
            'lucas.martins@example.com',
            'mariana.barbosa@example.com',
            'nicolas.teixeira@example.com',
            'olivia.ferreira@example.com'],

           ['paulo.cardoso@example.com',
            'quintino.araujo@example.com',
            'rafaela.dias@example.com',
            'samuel.nogueira@example.com',
            'talita.vieira@example.com'],

           ['victor.campos@example.com',
            'wilson.machado@example.com',
            'yasmin.fonseca@example.com']]

  :param emails: Lista com emails.
  :return: Lista com sublistas de até 5 emails.
  :raises TypeError: Caso a entrada não seja uma lista com valores string.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  if valida_lista_str(emails):
    contador_emails = 0
    fim = 5
    lista_final = []
    continuar = True
    while continuar:
      if contador_emails < len(emails):
        lista_5 = emails[contador_emails: fim]
        lista_final.append(lista_5)

        contador_emails = contador_emails + 5
        fim = fim + 5
      else:
        continuar = False

    return lista_final




In [34]:
evita_sobrecarga_emails(emails)

[['ana.silva@example.com',
  'bruno.santos@example.com',
  'carla.oliveira@example.com',
  'daniel.costa@example.com',
  'eduarda.lima@example.com'],
 ['felipe.rocha@example.com',
  'gabriela.alves@example.com',
  'henrique.melo@example.com',
  'isabela.ramos@example.com',
  'joao.pereira@example.com'],
 ['karina.gomes@example.com',
  'lucas.martins@example.com',
  'mariana.barbosa@example.com',
  'nicolas.teixeira@example.com',
  'olivia.ferreira@example.com'],
 ['paulo.cardoso@example.com',
  'quintino.araujo@example.com',
  'rafaela.dias@example.com',
  'samuel.nogueira@example.com',
  'talita.vieira@example.com'],
 ['victor.campos@example.com',
  'wilson.machado@example.com',
  'yasmin.fonseca@example.com']]

15. O marketing quer saber quais são as corporações dominantes na base de leads analisando os domínios corporativos.

- Objetivo: Dada uma lista de emails corporativos, extraia a parte após '@' de cada email e armazene os domínios únicos em um conjunto.

In [35]:
emails_corporativos = [
    "ana.silva@technova.com",
    "bruno.santos@globexcorp.com",
    "carla.oliveira@alphadata.com.br",
    "daniel.costa@zenithsystems.io",
    "eduarda.lima@orionsoft.com",
    "felipe.rocha@inovare.net",
    "gabriela.alves@bluewave.com.br",
    "henrique.melo@quantumlabs.ai",
    "isabela.ramos@nexustech.com",
    "joao.pereira@vertexgroup.com.br",
    "karina.gomes@skylineconsulting.com",
    "lucas.martins@omnidata.io",
    "mariana.barbosa@futurelink.com",
    "nicolas.teixeira@auroradigital.com.br",
    "olivia.ferreira@hyperiontech.com",
    "paulo.cardoso@evolutioncorp.net",
    "quintino.araujo@pixelworks.com.br",
    "rafaela.dias@innovaxis.com",
    "samuel.nogueira@starlightgroup.io",
    "talita.vieira@maximusdata.com.br",
    "victor.campos@cybercore.tech",
    "wilson.machado@primeanalytics.com",
    "yasmin.fonseca@solarisconsult.com"
]


In [36]:
def extrai_dominios_corporativos(emails_corp: list[str]) -> set[str]:

  """
  Recebe uma lista de emails corporativos e extrai seus domínios.
  Exemplo:
      >>> emails_corporativos = [
      ... "ana.silva@technova.com",
      ... "bruno.santos@globexcorp.com",
      ... "carla.oliveira@alphadata.com.br",
      ... "daniel.costa@zenithsystems.io",
      ... "eduarda.lima@orionsoft.com",
      ... "felipe.rocha@inovare.net",
      ... "gabriela.alves@bluewave.com.br",
      ... "henrique.melo@quantumlabs.ai",
      ... "isabela.ramos@nexustech.com",
      ... "joao.pereira@vertexgroup.com.br",
      ... "karina.gomes@skylineconsulting.com",
      ... "lucas.martins@omnidata.io",
      ... "mariana.barbosa@futurelink.com",
      ... "nicolas.teixeira@auroradigital.com.br",
      ... "olivia.ferreira@hyperiontech.com",
      ... "paulo.cardoso@evolutioncorp.net",
      ... "quintino.araujo@pixelworks.com.br",
      ... "rafaela.dias@innovaxis.com",
      ... "samuel.nogueira@starlightgroup.io",
      ... "talita.vieira@maximusdata.com.br",
      ... "victor.campos@cybercore.tech",
      ... "wilson.machado@primeanalytics.com",
      ... "yasmin.fonseca@solarisconsult.com"]

      >>> extrai_dominios_corporativos(emails_corporativos)
          { 'alphadata.com.br',
            'auroradigital.com.br',
            'bluewave.com.br',
            'cybercore.tech',
            'evolutioncorp.net',
            'futurelink.com',
            'globexcorp.com',
            'hyperiontech.com',
            'innovaxis.com',
            'inovare.net',
            'maximusdata.com.br',
            'nexustech.com',
            'omnidata.io',
            'orionsoft.com',
            'pixelworks.com.br',
            'primeanalytics.com',
            'quantumlabs.ai',
            'skylineconsulting.com',
            'solarisconsult.com',
            'starlightgroup.io',
            'technova.com',
            'vertexgroup.com.br',
            'zenithsy stems.io'}

  :param emails_corp: Lista com emails corporativos.
  :return: Conjunto com domínio dos emails.
  :raises TypeError: Caso a entrada não seja uma lista com valores string.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  valida_lista_str(emails_corp)

  dominios = {email[email.index('@') + 1: ] for email in emails_corp if '@' in email}

  return dominios


In [37]:
extrai_dominios_corporativos(emails_corporativos)

{'alphadata.com.br',
 'auroradigital.com.br',
 'bluewave.com.br',
 'cybercore.tech',
 'evolutioncorp.net',
 'futurelink.com',
 'globexcorp.com',
 'hyperiontech.com',
 'innovaxis.com',
 'inovare.net',
 'maximusdata.com.br',
 'nexustech.com',
 'omnidata.io',
 'orionsoft.com',
 'pixelworks.com.br',
 'primeanalytics.com',
 'quantumlabs.ai',
 'skylineconsulting.com',
 'solarisconsult.com',
 'starlightgroup.io',
 'technova.com',
 'vertexgroup.com.br',
 'zenithsystems.io'}

16. Situação: Você tem um dicionário onde a chave é o nome do funcionário e o valor é o departamento. Você precisa do inverso para buscas rápidas.

- Objetivo: Crie um novo dicionário onde as chaves sejam os nomes dos departamentos e os valores sejam listas com os nomes dos funcionários pertencentes.

In [38]:
funcionarios = {
    "Ana": "TI",
    "Bruno": "Financeiro",
    "Carla": "Recursos Humanos",
    "Daniel": "Marketing",
    "Eduarda": "TI"
}

In [39]:
def valida_dict(dicionario: dict) -> bool:

  if not isinstance(dicionario, dict):
    raise TypeError('A função espera um objeto do tipo Dict.')

  if not dicionario:
    raise ValueError('A função não espera um dicionário vazio.')

  for chave, valor in dicionario.items():
    if not isinstance(chave, str):
      raise TypeError(f'Valor inválido encontrado: {chave}')
    if not isinstance(valor, str):
      raise TypeError(f'Valor inválido encontrado: {valor}')

  return True

In [40]:
def converte_chave_valor(dict_func: dict[str, str]) -> dict[str, list[str]]:

  """
  Recebe um dicionário no qual a chave é o nome do funcionário e o valor é o departamento em que ele se encontra.
  Por fim, cria um novo dicionário no qual a chave é o nome do departamento e o valor é uma lista com todos os funcionários dele.
  Exemplo:
      >>> funcionarios = {
      ... "Ana": "TI",
      ... "Bruno": "Financeiro",
      ... "Carla": "Recursos Humanos",
      ... "Daniel": "Marketing",
      ... "Eduarda": "TI"}

      >>> converte_chave_valor(funcionarios)
         {'TI': ['Ana', 'Eduarda'],
          'Financeiro': ['Bruno'],
          'Recursos Humanos': ['Carla'],
          'Marketing': ['Daniel']}

  :param dict_func: dicionário com nome do funcionário e departamento.
  :return: dicionário com nome do departamento e lista de funcionários.
  :raises TypeError: Caso a entrada não seja um dicionário com chave e valor string.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  valida_dict(dict_func)

  novo_dicionario = {}

  for func, depart in dict_func.items():
      if depart not in novo_dicionario:
          novo_dicionario[depart] = [func]
      else:
          novo_dicionario[depart].append(func)

  return novo_dicionario




In [41]:
converte_chave_valor(funcionarios)

{'TI': ['Ana', 'Eduarda'],
 'Financeiro': ['Bruno'],
 'Recursos Humanos': ['Carla'],
 'Marketing': ['Daniel']}

17. Situação: Uma carga do banco de dados veio corrompida e inseriu valores 'None' na lista contendo os salários base da empresa.

- Objetivo: Escreva um script que conte quantos valores nulos existem e gere uma lista limpa substituindo os 'None' pelo valor zero.

In [42]:
salarios = [3500, 4200, None, 5100, 2800, None, 6000]

In [43]:
def valida_lista_corrompida(lista: list) -> bool:

    if not isinstance(lista, list):
        raise TypeError('A função espera um objeto do tipo List.')

    if not lista:
        raise ValueError('A função não espera uma lista vazia.')

    for item in lista:
        if not isinstance(item, (int, float, type(None))):
            raise TypeError(f'Valor inválido: {item}')

    return True

In [44]:
def limpa_lista_corrompida(lista: list) -> list[float]:

  """
  Recebe uma lista corrompida com os salários base da empresa.
  O objetivo é substituir os valores 'None' por 0(zero)

  Exemplo:
      >>> salarios = [3500, 4200, None, 5100, 2800, None, 6000]
      >>> limpa_lista_corrompida(salarios)
      [3500.0, 4200.0, 0.0, 5100.0, 2800.0, 0.0, 6000.0]


  :param lista: lista corrompida com os salários base da empresa.
  :return: lista limpa com os salários base da empresa.
  :raises TypeError: Caso a entrada não seja uma lista com valores int, float ou None.
  :raises ValueError: Caso a entrada esteja vazia.
  """
  valida_lista_corrompida(lista)

  print(f'Quantidade de valores nulos: {lista.count(None)}')

  return [0.0 if item is None else float(item) for item in lista]


limpa_lista_corrompida(salarios)

Quantidade de valores nulos: 2


[3500.0, 4200.0, 0.0, 5100.0, 2800.0, 0.0, 6000.0]

18. Situação: Você tem uma lista de IDs de clientes que compraram na Black Friday e outra de clientes que abriram a última Newsletter.

- Objetivo: Descubra quais clientes realizaram ambas as ações utilizando operações matemáticas aplicadas a conjuntos (sets)

In [45]:
clientes_black_friday = [1001, 1002, 1003, 1004, 1005]
clientes_newsletter = [1003, 1004, 1006, 1007, 1008]

In [46]:
def acoes_comuns(*, black_friday: list[int], newsletter: list[int]) -> set[int]:

  """
  Recebe uma lista de IDs de clientes que compraram na Black Friday;
  Recebe uma lista de IDs de clientes que abriram a última Newsletter.

  O objetivo é encontrar clientes que se encontram em ambas as listas.

  Exemplo:
      >>> clientes_black_friday = [1001, 1002, 1003, 1004, 1005]
      >>> clientes_newsletter = [1003, 1004, 1006, 1007, 1008]
      >>> acoes_comuns(black_friday= clientes_black_friday, newsletter = clientes_newsletter)
      {1003, 1004}


  :param black_friday: lista de IDs que compraram na Black Friday.
  :param newsletter: lista de IDs que abriram a última Newsletter.
  :return: conjunto de clientes presentes em ambas as listas.
  :raises TypeError: Caso a entrada não seja uma lista com valores int.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  valida_lista_int(black_friday)
  valida_lista_int(newsletter)

  bf = set(black_friday)
  nl = set(newsletter)

  return bf.intersection(nl)

acoes_comuns(black_friday= clientes_black_friday, newsletter = clientes_newsletter)


{1003, 1004}

19. Situação: Um dicionário armazena o ID do pedido como chave e uma lista com os valores dos itens comprados como valor.

- Objetivo: Escreva um loop que processe esse dicionário e imprima o ID do pedido junto com o valor médio gasto por item naquele pedido.


In [47]:
pedidos = {
    1001: [29.90, 15.50, 8.00],
    1002: [120.00],
    1003: [45.30, 22.10]
}

In [48]:
def valida_dict_list_float(dicionario: dict[int, list[float]]) -> bool:

  if not isinstance(dicionario, dict):
    raise TypeError('A função espera um objeto do tipo Dict.')

  if not dicionario:
    raise ValueError('A função não espera um dicionário vazio.')

  for chave, valor in dicionario.items():
    if not isinstance(chave, int):
      raise TypeError(f'Valor inválido encontrado: {chave}')
    if not isinstance(valor, list):
      raise TypeError(f'Valor inválido encontrado: {valor}')
    if not valor:
      raise ValueError('A função não espera uma lista vazia.')
    for item in valor:
      if not isinstance(item, float):
        raise TypeError(f'Valor inválido encontrado: {item}')

  return True

In [49]:
def processa_pedidos(pedidos: dict[int, list[float]]) -> None:

  """
  Recebe um dicionário no qual a Chave é o ID do pedido e o Valor são os valores comprados.
  O objetivo é processar os pedidos e imprimir o valor médio gasto por item.

  Exemplo:
      >>> pedidos = {
      ... 1001: [29.90, 15.50, 8.00],
      ... 1002: [120.00],
      ... 1003: [45.30, 22.10]}

      >>> processa_pedidos(pedidos)
          ID do pedido: 1001. Valor médio gasto: R$17.8
          ID do pedido: 1002. Valor médio gasto: R$120.0
          ID do pedido: 1003. Valor médio gasto: R$33.7


  :param pedidos: dicionário com os registros dos pedidos.
  :return: None
  :raises TypeError: Caso a entrada não seja um dicionário com chave Int e valor do tipo List de Float.
  :raises ValueError: Caso a entrada esteja vazia.
  """


  valida_dict_list_float(pedidos)

  for chave, valor in pedidos.items():
    print(f'ID do pedido: {chave}. Valor médio gasto: R${sum(valor)/len(valor)}')

processa_pedidos(pedidos)

ID do pedido: 1001. Valor médio gasto: R$17.8
ID do pedido: 1002. Valor médio gasto: R$120.0
ID do pedido: 1003. Valor médio gasto: R$33.7


20. Situação: O RH enviou uma lista de dicionários contendo informações de colaboradores, incluindo o campo 'ano_contratacao'.

- Objetivo: Extraia o nome de todos os colaboradores contratados a partir do ano de 2024 utilizando estruturas condicionais.

In [50]:
colaboradores = [
    {"nome": "Ana Silva", "cargo": "Analista de Dados", "ano_contratacao": 2022},
    {"nome": "Carlos Souza", "cargo": "Desenvolvedor", "ano_contratacao": 2019},
    {"nome": "Beatriz Lima", "cargo": "Gerente de RH", "ano_contratacao": 2025},
    {"nome": "Diego Alves", "cargo": "Estagiário", "ano_contratacao": 2024},
    {"nome": "Fernanda Costa", "cargo": "Cientista de Dados", "ano_contratacao": 2021},
]

In [51]:
def valida_list_dict (lista: list[dict[str, str|int]]) -> bool:

  if not isinstance(lista, list):
    raise TypeError('A função espera um objeto do tipo List.')

  if not lista:
    raise ValueError('A função não espera uma lista vazia.')

  for dicionario in lista:
    if not isinstance(dicionario, dict):
      raise TypeError(f'Valor inválido encontrado: {dicionario}')

    for chave, valor in dicionario.items():
      if not isinstance(chave, str):
        raise TypeError(f'Valor inválido encontrado: {chave}')
      if not isinstance(valor, (str, int)):
        raise TypeError(f'Valor inválido encontrado: {valor}')

  return True

In [52]:
def extrai_colaboradores_2024(colaboradores: list[dict[str, str | int]]) -> list[str]:

  """
  Recebe uma lista de dicionários que contêm dados dos colaboradores.
  O objetivo é extrair o nome dos colaboradores que foram contratados a partir do ano de 2024.

  Exemplo:
      >>> colaboradores = [
      ... {"nome": "Ana Silva", "cargo": "Analista de Dados", "ano_contratacao": 2022},
      ... {"nome": "Carlos Souza", "cargo": "Desenvolvedor", "ano_contratacao": 2019},
      ... {"nome": "Beatriz Lima", "cargo": "Gerente de RH", "ano_contratacao": 2025},
      ... {"nome": "Diego Alves", "cargo": "Estagiário", "ano_contratacao": 2024},
      ... {"nome": "Fernanda Costa", "cargo": "Cientista de Dados", "ano_contratacao": 2021}]
      >>> extrai_colaboradores_2024(colaboradores)
          ['Beatriz Lima', 'Diego Alves']


  :param colaboradores: lista de dicionários com os registros dos colaboradores.
  :return: lista com nome dos colaboradores que foram contratados a partir de 2024.
  :raises TypeError: Caso a entrada não seja uma lista de dicionários, com chave string e valores string ou int.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  valida_list_dict(colaboradores)

  func_2024 = [colaborador["nome"] for colaborador in colaboradores if colaborador["ano_contratacao"] >= 2024]

  return func_2024

In [53]:
extrai_colaboradores_2024(colaboradores)

['Beatriz Lima', 'Diego Alves']

21. Situação: O SAC disponibilizou uma lista com feedbacks em texto enviados pelos usuários no aplicativo.

- Objetivo: Crie uma lista de palavras negativas. Verifique quantos feedbacks contêm pelo menos uma dessas palavras para mensurar a taxa de reclamações.

In [54]:
palavras_negativas = [
      "ruim", "péssimo", "péssima", "horrível", "lento", "lenta", "travando",
      "quebrado", "insatisfeito", "insatisfeita", "decepcionado", "decepcionada", "problema",
      "errado", "errada", "falha", "demora", "caro", "difícil", "confuso", "confusa"]

feedbacks = [
    "O aplicativo é muito lento para carregar as informações.",
    "Adorei a nova atualização, ficou muito mais rápido!",
    "Tive um problema sério ao tentar fazer login no sistema.",
    "O atendimento foi excelente, resolveram minha dúvida rapidamente.",
    "O app fica travando toda vez que tento abrir o relatório.",
    "Interface confusa, não consegui encontrar o que precisava.",
    "Ótima experiência, recomendo para todos os colegas.",
    "Estou decepcionado com a demora no suporte técnico.",
    "Funciona perfeitamente, sem nenhum erro até agora.",
    "O sistema quebrado me fez perder horas de trabalho.",
]

In [55]:
def verifica_taxa_reclamacoes(feedbacks: list[str], palavras: list[str]) -> str:

  """
  Recebe duas listas: uma de palavras negativas e outra de reclamações feitas no SAC.
  O objetivo é extrair os feedbacks que contêm as palavras da lista de palavras negativas.

  Exemplo:

      >>> palavras_negativas = [
      ... "ruim", "péssimo", "péssima", "horrível", "lento", "lenta", "travando",
      ... "quebrado", "insatisfeito", "insatisfeita", "decepcionado", "decepcionada", "problema",
      ... "errado", "errada", "falha", "demora", "caro", "difícil", "confuso", "confusa"]

      >>> feedbacks = [
      ... "O aplicativo é muito lento para carregar as informações.",
      ... "Adorei a nova atualização, ficou muito mais rápido!",
      ... "Tive um problema sério ao tentar fazer login no sistema.",
      ... "O atendimento foi excelente, resolveram minha dúvida rapidamente.",
      ... "O app fica travando toda vez que tento abrir o relatório.",
      ... "Interface confusa, não consegui encontrar o que precisava.",
      ... "Ótima experiência, recomendo para todos os colegas.",
      ... "Estou decepcionado com a demora no suporte técnico.",
      ... "Funciona perfeitamente, sem nenhum erro até agora.",
      ... "O sistema quebrado me fez perder horas de trabalho."]

      >>> verifica_taxa_reclamacoes(feedbacks, palavras_negativas)
          'Taxa de reclamações: 60.0%'

  :param feedbacks: lista de feedbacks disponibilizada pelo SAC.
  :param palavras: lista de palavras negativas.
  :return: taxa de reclamações
  :raises TypeError: Caso a entrada não seja uma lista de string.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  valida_lista_str(feedbacks)

  reclamacoes = [feedback for feedback in feedbacks if any(palavra in feedback.lower() for palavra in palavras)]

  taxa_reclamacoes = (len(reclamacoes) / len(feedbacks)) * 100

  return (f'Taxa de reclamações: {taxa_reclamacoes:.1f}%')

verifica_taxa_reclamacoes(feedbacks, palavras_negativas)

'Taxa de reclamações: 60.0%'

22. Situação: Planilhas enviadas por usuários costumam conter colunas com espaçoes extras, letras maiúsculas bagunçadas e acentos.

- Objetivo: Dada uma lista de nomes de colunas originais, aplique transformações de string para deixá-las em letras minúsculas, sem acentos e trocando espaços por '_'.

In [56]:
colunas = [
    " Nome Completo ",
    "IDADE",
    "e-mail ",
    "Data де Nascimento",
    " cidade",
    "SALÁRIO",
    "Departamento ",
    "Nº Matrícula",
    "telefone_Contato",
    " Área  de Atuação "
]

In [57]:
import unicodedata

def normaliza_colunas(colunas: list[str]) -> list[str]:

  """
  Recebe uma lista de strings com formatação bagunçada.
  O objetivo é deixar a string com letras minúsculas, sem acentos e trocar espaços por "_".

  Exemplo:

      >>> colunas = [
      ... " Nome Completo ",
      ... "IDADE",
      ... "e-mail ",
      ... "Data де Nascimento",
      ... " cidade",
      ... "SALÁRIO",
      ... "Departamento ",
      ... "Nº Matrícula",
      ... "telefone_Contato",
      ... " Área  de Atuação "
]

      >>> normaliza_colunas(colunas)
          ['nome_completo',
           'idade',
           'e-mail',
           'data_nascimento',
           'cidade',
           'salario',
           'departamento',
           'numero_matricula',
           'telefone_contato',
           'area_de_atuacao']

  :param colunas: lista de strings que representam nomes de colunas com formatação bagunçada.
  :return: lista de strings com formatação normalizada.
  :raises TypeError: Caso a entrada não seja uma lista de string.
  :raises ValueError: Caso a entrada esteja vazia.
  """

  valida_lista_str(colunas)

  colunas_normalizadas = []

  for variavel in colunas:
    variavel_formatada1 = variavel.replace('Nº', 'numero')
    variavel_formatada = unicodedata.normalize('NFKD', variavel_formatada1).encode('ASCII', 'ignore').decode('ASCII').strip().lower().replace(' ', '_').replace('__', '_')
    colunas_normalizadas.append(variavel_formatada)

  return colunas_normalizadas

normaliza_colunas(colunas)


['nome_completo',
 'idade',
 'e-mail',
 'data_nascimento',
 'cidade',
 'salario',
 'departamento',
 'numero_matricula',
 'telefone_contato',
 'area_de_atuacao']

23. Situação: Logs de eventos mostram tuplas com (id_usuario, timestamp_inicio, timestamp_fim) medidos em segundos corridos do dia.

- Objetivo: Calcule a duração média de sessão de todos os usuários dessa lista de dados brutos.

In [58]:
logs = [
    (101, 3600, 3900),    # Usuário 101: 01:00:00 até 01:05:00
    (102, 4500, 5400),    # Usuário 102: 01:15:00 até 01:30:00
    (101, 7200, 8100),    # Usuário 101: 02:00:00 até 02:15:00
    (103, 10800, 11100),  # Usuário 103: 03:00:00 até 03:05:00
    (104, 43200, 45000),  # Usuário 104: 12:00:00 até 12:30:00
]

In [59]:
def valida_list_tupla_int(lista: list[tuple[int, int, int]]) -> bool:

    if not isinstance(lista, list):
        raise TypeError('A função espera um objeto do tipo List.')

    if not lista:
        raise ValueError('A função não espera uma lista vazia.')

    for item in lista:

        if not isinstance(item, tuple):
            raise TypeError(f'Valor inválido: {item}')

        if len(item) != 3:
            raise ValueError('Cada tupla deve conter (id_usuario, timestamp_inicio, timestamp_fim)')

        for i in item:
          if not isinstance(i, int):
            raise TypeError(f'Valor inválido: {i}')

        if item[1] > item[2]:
            raise ValueError(f'Timestamp final menor que o inicial: {item[2]}')

    return True


In [60]:
def calcula_duracao_media (sessao: list[tuple[int, int, int]]) -> None:

  """
  Recebe uma lista de tuplas com (id_usuario, timestamp_inicio, timestamp_fim).
  O objetivo é calcular a duração média (em segundos) de sessão de todos os id_usuario.

  Exemplo:

      >>> logs = [
      ... (101, 3600, 3900),    # Usuário 101: 01:00:00 até 01:05:00
      ... (102, 4500, 5400),    # Usuário 102: 01:15:00 até 01:30:00
      ... (101, 7200, 8100),    # Usuário 101: 02:00:00 até 02:15:00
      ... (103, 10800, 11100),  # Usuário 103: 03:00:00 até 03:05:00
      ... (104, 43200, 45000),  # Usuário 104: 12:00:00 até 12:30:00 ]

      >>> calcula_duracao_media(sessao)
          Duração média de todos os usuários: 840.0 segundos.

  :param sessao: lista de tuplas com logs.
  :return: None
  :raises TypeError: Caso a entrada não seja uma lista de tupla de inteiros.
  :raises ValueError: Caso a entrada esteja vazia ou a tupla tenha menos que 3 elementos ou o timestamp final seja menor que o inicial.
  """


  valida_list_tupla_int(sessao)

  lista_duracoes = [duracao[2] - duracao[1] for duracao in sessao]

  media = sum(lista_duracoes)/len(lista_duracoes)

  print(f'Duração média de todos os usuários: {media} segundos.')

In [61]:
calcula_duracao_media(logs)

Duração média de todos os usuários: 840.0 segundos.


24. Situação: Um usuário tenta acessar uma funcionalidade no Tableau Embed que requer as permissões {'admin', 'viewer', 'editor'}.

- Objetivo: Dado um conjunto com as permissões atuais do usuário logado, verifique se ele possui todas as permissões necessárias utilizando métodos do conjunto.

In [62]:
permissoes_usuario = {'viewer'}

In [63]:
def valida_set_str(conjunto: set[str]) -> bool:

  if not isinstance(conjunto, set):
        raise TypeError('A função espera um objeto do tipo Set.')

  for item in conjunto:
       if not isinstance(item, str):
          raise TypeError(f'Valor inválido: {item}')

  return True


In [64]:
def verifica_permissoes_tableau(p_usuario: set[str]) -> None:

  """
  Recebe um conjunto de permissões do usuário no Tableau.
  O objetivo é verificar se ele possui todas as permissões necessária.

  Exemplo:

      >>> permissoes_usuario = {'viewer'}

      >>> verifica_permissoes_tableau(p_usuario)
          O usuário não possui todas as permissões necessárias.
          Permissões que faltam: {'editor', 'admin'}

  :param p_usuario: conjunto de permissões do usuário.
  :return: None
  :raises TypeError: Caso a entrada não seja um conjunto de strings.
  """

  valida_set_str(p_usuario)
  permissoes_requeridas = {'admin', 'viewer', 'editor'}

  if permissoes_requeridas.intersection(p_usuario) == permissoes_requeridas:
    print('O usuário possui todas as permissões necessárias.')
  else:
    print('O usuário não possui todas as permissões necessárias.')
    print(f'Permissões que faltam: {permissoes_requeridas - p_usuario}')

In [65]:
verifica_permissoes_tableau(permissoes_usuario)

O usuário não possui todas as permissões necessárias.
Permissões que faltam: {'editor', 'admin'}


25. Situação: O diretor precisa de um resumo textual rápido a partir de um dicionário contendo métricas de performance da Squad de BI.

- Objetivo: Formate o dicionário {'entregas':15, 'atrasos': 2, 'satisfacao': 9.4} em uma string multilinhas elegante e profissional para envio por e-mail.

In [66]:
performance = {'entregas': 15, 'atrasos': 2, 'satisfacao': 9.4}

entregas, atrasos, satisfacao = performance.values()

print('Assunto: Performance da Squad de BI \n\n'
      'Prezados, \n\n'
      'Segue o resumo das métricas do período:\n\n'
     f'1. Entregas: {entregas}.\n'
     f'2. Atrasos: {atrasos}.\n'
     f'3. Satisfação: {satisfacao}.')

Assunto: Performance da Squad de BI 

Prezados, 

Segue o resumo das métricas do período:

1. Entregas: 15.
2. Atrasos: 2.
3. Satisfação: 9.4.


### Introdução ao NumPy: Criação, Tipagem e Indexação Avançada. (Exercícios 26 a 50).


In [67]:
import numpy as np

26. Situação: Você precisa estruturar a base de dados para um gráfico de linha contendo os 12 meses do ano para projeções de vendas.

- Objetivo: Crie um array unidimensional do NumPy contendo os números inteiros de 1 a 12 utilizando uma função nativa de inicialização por intervalos.

In [68]:
meses_do_ano = np.arange(1, 13)
meses_do_ano

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

27. Situação: Você está preparando um modelo de simulação para uma arquitetura com 5 servidores e 24 horas do dia monitoradas.

- Objetivo: Crie uma matriz bidimensional preenchida completamente com zeros, com formato (5, 24), representando o estado inicial estável de cada servidor.

In [69]:
servidores = np.zeros((5,24), dtype = int)
print(servidores)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


28. Situação: O marketing fará testes A/B de precificação elástica, variando o preço de um produto de 19,90 até 99,90 reais em exatamente 10 faixas.

- Objetivo: Utilize a função ideal do numpy para gerar um array contendo esses 10 preços com espaçamento linear idêntico entre eles.

In [70]:
produto = np.linspace(19.90, 99.90, num = 10)
print(produto)

[19.9        28.78888889 37.67777778 46.56666667 55.45555556 64.34444444
 73.23333333 82.12222222 91.01111111 99.9       ]


29. Situação: Para justificar o uso do NumPy na engenharia de dados da empresa, você precisa provar a economia de memória física.

- Objetivo: Crie uma lista com 1 milhão de inteiros e um array NumPy equivalente. Imprima o tamanho em bytes consumido por cada um usando os atributos corretos.

In [71]:
import sys

lista = [i for i in range(1, 1000001)]
array = np.arange(1, 1000001)

print(sys.getsizeof(lista))
print((array.itemsize) * (array.size))


8448728
8000000


30. Situação: Um array NumPy contendo milhões de IDs de transações foi importado por padrão como float64, consumindo memória desnecessária.

- Objetivo: Converta explicitamente o tipo do array (cast) para int32 utilizando os métodos do NumPy e verifique a alteração da propriedade dtype.


In [72]:
ids_transacoes = np.array(
    [100001, 100002, 100003, 100004, 100005],
    dtype=np.float64
)

print(ids_transacoes.dtype)

ids_transacoes = ids_transacoes.astype(np.int32)

print(ids_transacoes.dtype)

float64
int32


31. Situação: Você tem uma matriz NumPy onde as linhas representam 4 regiões (Norte, Sul, Leste, Oeste) e as colunas os 12 meses do ano.

- Objetivo: Escreva a linha de código que extrai o faturamento exato do terceiro mês da quarta região (lembre-se da indexação base zero).


In [73]:
faturamento = np.array([
    [100.50, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220],  # Norte
    [90.0,  95,  100, 110, 120.2, 130, 140, 150, 160, 170.88, 180, 190],  # Sul
    [80.0,  85,  90.1,  95,  100, 110, 120.35, 130, 140, 150, 160, 170],  # Leste
    [70,  75,  80,  85,  90.46,  95,  100, 105, 110, 115.90, 120, 125]   # Oeste
])

print(faturamento)

print(faturamento[3][2])

[[100.5  120.   130.   140.   150.   160.   170.   180.   190.   200.
  210.   220.  ]
 [ 90.    95.   100.   110.   120.2  130.   140.   150.   160.   170.88
  180.   190.  ]
 [ 80.    85.    90.1   95.   100.   110.   120.35 130.   140.   150.
  160.   170.  ]
 [ 70.    75.    80.    85.    90.46  95.   100.   105.   110.   115.9
  120.   125.  ]]
80.0


32. Situação: Utilizando a mesma matriz de faturamento multirregional (4 regiões x 12 meses), o CFO soliciou apenas os dados do Q1 (meses 1, 2 e 3).

- Objetivo: Realize um fatiamento (slicing) bidimensional para extrair as informações do primeiro trimestre de todas as regiões simultaneamente.

In [74]:
faturamento[:, [0, 1, 2]]

array([[100.5, 120. , 130. ],
       [ 90. ,  95. , 100. ],
       [ 80. ,  85. ,  90.1],
       [ 70. ,  75. ,  80. ]])

33. Situação: Você calculou uma matriz 5x5 de correlação de Pearson entre as métricas do PowerBI e precisa isolar a diagonal principal (auto-correlação).

- Objetivo: Utilize a função específica do NumPy para extrair os elementos da diagonal dessa matriz em um vetor unidimensional.

In [75]:
dados = np.array([
    [100, 150, 200, 250, 300],  # vendas
    [20, 30, 40, 50, 60],       # lucro
    [50, 55, 70, 80, 95],       # clientes
    [80, 90, 120, 130, 150],    # custos
    [15, 20, 25, 35, 40]        # margem
])

correlacao = np.corrcoef(dados)

print(correlacao)


print(np.diagonal(correlacao))

[[1.         1.         0.98976241 0.98787834 0.99124071]
 [1.         1.         0.98976241 0.98787834 0.99124071]
 [0.98976241 0.98976241 1.         0.99193535 0.98437404]
 [0.98787834 0.98787834 0.99193535 1.         0.97085578]
 [0.99124071 0.99124071 0.98437404 0.97085578 1.        ]]
[1. 1. 1. 1. 1.]


34. Situação: Um array unidimensional de faturamento diário veio ordenado do dia mais recente para o mais antigo.

- Objetivo: inverta a ordem dos elementos do array usando técnicas de slicing clássicas aplicadas a arrays NumPy para deixá-lo em ordem cronológica correta.

In [76]:
faturamento_diario = np.array([
    12500,  # hoje
    11800,  # ontem
    13200,  # 2 dias atrás
    11950,  # 3 dias atrás
    12100,  # 4 dias atrás
    11700,  # 5 dias atrás
    11500   # 6 dias atrás
])

print(faturamento_diario)

print(faturamento_diario[::-1])

[12500 11800 13200 11950 12100 11700 11500]
[11500 11700 12100 11950 13200 11800 12500]


35. Você tem um array contendo as taxas de conversão de 50 campanhas de marketing digital.

- Objetivo: Crie um filtro booleano que retorne um novo array apenas com as taxas de conversão superiores a 5.5%.

In [77]:
taxas_conversao = np.array([
    0.021, 0.034, 0.018, 0.045, 0.029,
    0.037, 0.025, 0.041, 0.019, 0.032,
    0.028, 0.051, 0.022, 0.039, 0.027,
    0.043, 0.031, 0.024, 0.035, 0.020,
    0.048, 0.026, 0.033, 0.017, 0.046,
    0.030, 0.023, 0.040, 0.036, 0.021,
    0.049, 0.028, 0.038, 0.025, 0.044,
    0.056, 0.034, 0.018, 0.042, 0.027,
    0.050, 0.024, 0.037, 0.031, 0.022,
    0.045, 0.026, 0.039, 0.020, 0.047
])

taxas_conversao[taxas_conversao > 0.055]


array([0.056])

36. Devido a um BUG no ERP, algumas quantidades devolvidas foram registradas incorretamente como valores negativos em um lote.

- Objetivo: Utilize indexação condicional booleana para localizar todos os valores menores que zero em um array NumPy e substitua-os imediatamente por 0.

In [78]:
quantidades = np.array([
    120,   # venda normal
    85,    # venda normal
    -15,   # devolução registrada incorretamente
    90,    # venda normal
    -8,    # devolução registrada incorretamente
    150,   # venda normal
    -20    # devolução registrada incorretamente
])

print(quantidades)

quantidades[quantidades < 0] = 0

print(quantidades)



[120  85 -15  90  -8 150 -20]
[120  85   0  90   0 150   0]


37. Um array armazena o número de requisições por hora recebidas em uma API de dados.

- Objetivo: Gere uma máscara booleana (True/False) indicando quais horas do dia sofreram picos de tráfego superiores a 10.000 requisições.

In [79]:
requisicoes_por_hora = np.array([
    120, 95, 80, 65, 70, 110,
    250, 480, 720, 850, 920, 980,
    1050, 1100, 1080, 1020, 950, 890,
    760, 650, 540, 420, 300, 180, 10500
])

print(requisicoes_por_hora)

print(requisicoes_por_hora > 10000)

[  120    95    80    65    70   110   250   480   720   850   920   980
  1050  1100  1080  1020   950   890   760   650   540   420   300   180
 10500]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
  True]


38. Você tem um array com faturamento de 100 filiais da empresa. A diretoria quer avaliar especificamente as filiais de índices 0, 15, 42 e 99.

- Objetivo: Utilize as técnicas de Fancy Indexing (passando uma lista de inteiros como índice) para extrair os valores dessas lojas específicas.

In [80]:
faturamento = np.array([
    150000, 180000, 220000, 175000, 210000,
    195000, 205000, 230000, 190000, 215000,
    250000, 185000, 200000, 240000, 170000,
    260000, 225000, 210000, 195000, 205000,
    180000, 215000, 235000, 190000, 220000,
    245000, 200000, 175000, 230000, 210000,
    195000, 250000, 185000, 220000, 205000,
    240000, 190000, 225000, 210000, 200000,
    235000, 180000, 270000, 195000, 215000,
    245000, 205000, 190000, 220000, 250000,
    175000, 230000, 210000, 195000, 240000,
    200000, 225000, 185000, 215000, 235000,
    190000, 245000, 205000, 180000, 220000,
    250000, 195000, 230000, 210000, 185000,
    240000, 200000, 225000, 190000, 215000,
    235000, 205000, 250000, 180000, 220000,
    195000, 245000, 210000, 185000, 230000,
    200000, 240000, 215000, 190000, 225000,
    250000, 205000, 180000, 235000, 210000,
    195000, 245000, 220000, 200000, 260000
])

print(faturamento[[0, 15, 42, 99]])

[150000 260000 270000 260000]


39. Situação: O diretor precisa saber qual filial obteve o maior faturamento histórico cadastrado em um array unidimensional.

- Objetivo: Encontre o índice (posição) do maior valor do array utilizando a função ideal do NumPy para essa busca sem usar loops.

In [81]:
np.where(faturamento == np.max(faturamento))

(array([42]),)

40. Situação: Um array armazena o percentual de evasão dos clientes por filial. Valores acima de 15% disparam alertas regulatórios.

- Objetivo: Retorne um array contendo os índices exatos de todas as filiais que estão violando a meta de segurança operacional.

In [82]:
evasao = np.array([
    8.5, 12.3, 16.8, 9.7, 14.2,
    18.1, 11.5, 13.9, 21.4, 10.8,
    15.2, 7.9, 17.6, 12.7, 14.8
])

print(evasao)

print(np.where(evasao > 15))

[ 8.5 12.3 16.8  9.7 14.2 18.1 11.5 13.9 21.4 10.8 15.2  7.9 17.6 12.7
 14.8]
(array([ 2,  5,  8, 10, 12]),)


41. Situação: Uma matriz representa 1000 linhas de transações financeiras diárias organizadas sequencialmente por tempo.

- Objetivo: Extraia as últimas 10 linhas da matriz contendo todas as suas colunas originais utilizando fatiamento com índices negativos.

In [83]:
transacoes = np.random.uniform(100, 1000, size = [1000,4])
print(transacoes[-10:, :])

[[209.71025422 103.55477026 890.03846548 941.97098057]
 [378.08120951 454.0260849  927.69486704 158.05443927]
 [762.85308976 257.63352047 196.31586209 172.81879981]
 [665.35195538 129.94263406 968.6569452  988.150988  ]
 [553.53287925 695.75400788 994.85882479 212.53006397]
 [546.69255401 677.98372035 521.7459895  899.00195697]
 [167.0638486  297.19236844 762.75605492 402.42746337]
 [973.47121419 865.37027567 853.57148938 641.28376481]
 [709.11947515 405.99397782 582.89476086 467.95669827]
 [786.86461479 503.6270373  917.40676677 969.692201  ]]


42. Situação: Para realizar cálculos de álgebra linear em um modelo econométrico de regressão, você precisa de uma matriz de identidade 4x4.

- Objetivo: Gere uma matriz usando a função do NumPy e imprima na tela o seu formato('shape') e número de dimensões ('ndim').

In [84]:
matriz_identidade = np.eye(4,4)
print(matriz_identidade)
print(matriz_identidade.shape)
print(matriz_identidade.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
2


43. Situação: O banco de dados preenche campos vazios ou nulos de faturamento com o código inteiro '-9999'.

- Objetivo: Localize esses códigos no array NumPy e substitua-os pelo marcador oficial de dados ausentes do NumPy('np.nan')

In [85]:
faturamento = np.array([
    125000,
    98000,
    -9999,   # valor ausente
    143000,
    87000,
    -9999,   # valor ausente
    156000,
    112000,
    -9999,   # valor ausente
    134000
], dtype=float)

print(faturamento)

print(np.where(faturamento == -9999))


faturamento[faturamento == -9999] = np.nan

print(faturamento)

[125000.  98000.  -9999. 143000.  87000.  -9999. 156000. 112000.  -9999.
 134000.]
(array([2, 5, 8]),)
[125000.  98000.     nan 143000.  87000.     nan 156000. 112000.     nan
 134000.]


44. O time de Recursos Humanos precisa mapear funcionários que ganham entre 5.000 reais e 12.000 reais em um array de salários.

- Objetivo: Escreva uma expressão condicional composta (usando operadores lógicos bitwise do NumPy) para filtrar esse intervalo exato de dados.

In [86]:
salarios = np.array([
    3200, 4800, 5500, 6200, 7500,
    8900, 12000, 13500, 4200, 9800,
    11000, 15000, 6800, 5300, 17000
])

print(salarios)

funcionarios_salario = salarios[(salarios >= 5000) & (salarios <= 12000)]

print(np.sort(funcionarios_salario))



[ 3200  4800  5500  6200  7500  8900 12000 13500  4200  9800 11000 15000
  6800  5300 17000]
[ 5300  5500  6200  6800  7500  8900  9800 11000 12000]


45. Situação: Para acelerar a renderização de um relatório preliminar no Tableau, você decidiu coletar uma amostra pegando uma linha a cada duas da matriz.

- Objetivo: Aplique um fatiamento com passos específicos ('step') na primeira dimensão de uma matriz de dados para extrair a amostra.

In [87]:
relatorio = np.array([
    [101, 5000, 120],
    [102, 4800, 115],
    [103, 5200, 130],
    [104, 5100, 125],
    [105, 5500, 140],
    [106, 5300, 135],
    [107, 5700, 150],
    [108, 5600, 145]
])
print(relatorio[::2])

[[ 101 5000  120]
 [ 103 5200  130]
 [ 105 5500  140]
 [ 107 5700  150]]


46. Situação: Um array contém o total de vendas convertidas por 200 vendedores da empresa.

- Objetivo: Utilize a soma de uma máscara booleana para calcular rapidamente o número exato de vendedores que venderam mais de 50 itens.

In [88]:
vendas = np.array([
    45, 38, 52, 61, 47, 29, 55, 42, 50, 37,
    63, 58, 41, 49, 46, 33, 57, 44, 51, 39,
    48, 62, 35, 53, 40, 59, 43, 56, 36, 54,
    47, 60, 38, 52, 45, 58, 41, 49, 34, 55,
    46, 61, 37, 50, 42, 57, 39, 53, 44, 59,
    48, 62, 35, 51, 40, 56, 43, 54, 36, 60,
    47, 58, 38, 52, 45, 61, 41, 49, 34, 55,
    46, 57, 37, 50, 42, 59, 39, 53, 44, 62,
    48, 51, 35, 56, 40, 54, 43, 60, 36, 58,
    47, 52, 38, 61, 45, 49, 41, 55, 34, 57,
    46, 50, 37, 59, 42, 53, 39, 62, 44, 51,
    48, 56, 35, 54, 40, 60, 43, 58, 36, 52,
    47, 61, 38, 49, 45, 55, 41, 57, 34, 50,
    46, 59, 37, 53, 42, 62, 39, 51, 44, 56,
    48, 54, 35, 60, 40, 58, 43, 52, 36, 61,
    47, 49, 38, 55, 45, 57, 41, 50, 34, 59,
    46, 53, 37, 62, 42, 51, 39, 56, 44, 54,
    48, 60, 35, 58, 40, 52, 43, 61, 36, 49,
    47, 55, 38, 57, 45, 50, 41, 59, 34, 53,
    46, 62, 37, 51, 42, 56, 39, 54, 44, 60
])

print(vendas.shape)

mascara_booleana = vendas > 50
print(mascara_booleana.sum())

print(mascara_booleana)

(200,)
85
[False False  True  True False False  True False False False  True  True
 False False False False  True False  True False False  True False  True
 False  True False  True False  True False  True False  True False  True
 False False False  True False  True False False False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False False False  True False  True
 False False False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False False
 False  True False  True False False False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False False False  True False  True False False False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False False False  True False  True
 False False False  True False  True Fals

47. Situação: Você precisa fazer testes drásticos alterando valores em um array de faturamento, mas não pode corromper o array original na memória.

- Objetivo: Crie uma cópia independente do array utilizando a função correta do NumPy e prove que alterações no novo array não afetam o original.

In [89]:
faturamento = np.array([
    125000,
    98000,
    143000,
    87000,
    156000,
    112000,
    134000
])

print(faturamento)

copia_faturamento = faturamento.copy()

print(copia_faturamento)

copia_faturamento[0] = 0

print(faturamento)
print(copia_faturamento)

[125000  98000 143000  87000 156000 112000 134000]
[125000  98000 143000  87000 156000 112000 134000]
[125000  98000 143000  87000 156000 112000 134000]
[     0  98000 143000  87000 156000 112000 134000]


48. Situação: Uma matriz 5x5 guarda pontuações de eficiência de processos. Você precisa extrair a submatriz central de tamanho 3x3.

- Objetivo: Utilize o fatiamento coordenado nas linhas e colunas para capturar as linhas de índice 1 a 3 e colunas de índice 1 a 3.

In [90]:
eficiencia_processos = np.arange(1, 26)   
eficiencia_processos = eficiencia_processos.reshape(5,5)  

print(eficiencia_processos)
print('\n')
print(eficiencia_processos[1:4, 1:4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


49. Situação: Você tentou converter uma lista Python contendo inteiros e uma string ([100, 200, 'Erro']) diretamente para um array NumPy.

- Objetivo: Crie esse array e verifique para qual tipo de dado o NumPy converteu todos os elementos por coerção automática para evitar quebras lógicas.

In [91]:
lista_python = [100, 200, 'Erro']

# todo array tem um único dtype.

array = np.array(lista_python)

print(array.dtype)

<U21


50. Situação: Seus dados estão sendo estruturados em um formato de cubo OLAP contendo (2 Anos, 12 Meses, 5 Regiões.)

- Objetivo: Crie um array com esse formato tridimensional contendo valores sequenciais quaisquer e use atributos para verificar o número total de elementos (size).

In [92]:
array = np.arange(1, 121)

print(array)

array_tridimensional = array.reshape(2,12,5)

print(array_tridimensional)

print(array_tridimensional.size)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]
[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]
  [ 51  52  53  54  55]
  [ 56  57  58  59  60]]

 [[ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]
  [ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]
  [101 102 103 104 105]
  [106